//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 12:18:32 AM CST 
//


package com.sdn.app;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="strict" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flow-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="cookie_mask" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="cookie" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="table_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="hard-timeout" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="idle-timeout" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="installHw" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="instructions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="instruction">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="apply-actions">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="action" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="output-action" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="output-node-connector" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                           &lt;element name="max-length" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="set-queue-action" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                           &lt;element name="queue-id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="match">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ethernet-match">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ethernet-type">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ethernet-destination">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "strict",
    "flowName",
    "id",
    "cookieMask",
    "cookie",
    "tableId",
    "priority",
    "hardTimeout",
    "idleTimeout",
    "installHw",
    "instructions",
    "match"
})
@XmlRootElement(name = "flow")
public class Flow {

    @XmlElement(required = true)
    protected String strict;
    @XmlElement(name = "flow-name", required = true)
    protected String flowName;
    protected byte id;
    @XmlElement(name = "cookie_mask")
    protected short cookieMask;
    protected byte cookie;
    @XmlElement(name = "table_id")
    protected byte tableId;
    protected byte priority;
    @XmlElement(name = "hard-timeout")
    protected short hardTimeout;
    @XmlElement(name = "idle-timeout")
    protected short idleTimeout;
    @XmlElement(required = true)
    protected String installHw;
    @XmlElement(required = true)
    protected Flow.Instructions instructions;
    @XmlElement(required = true)
    protected Flow.Match match;

    /**
     * Gets the value of the strict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrict() {
        return strict;
    }

    /**
     * Sets the value of the strict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrict(String value) {
        this.strict = value;
    }

    /**
     * Gets the value of the flowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowName() {
        return flowName;
    }

    /**
     * Sets the value of the flowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowName(String value) {
        this.flowName = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public byte getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(byte value) {
        this.id = value;
    }

    /**
     * Gets the value of the cookieMask property.
     * 
     */
    public short getCookieMask() {
        return cookieMask;
    }

    /**
     * Sets the value of the cookieMask property.
     * 
     */
    public void setCookieMask(short value) {
        this.cookieMask = value;
    }

    /**
     * Gets the value of the cookie property.
     * 
     */
    public byte getCookie() {
        return cookie;
    }

    /**
     * Sets the value of the cookie property.
     * 
     */
    public void setCookie(byte value) {
        this.cookie = value;
    }

    /**
     * Gets the value of the tableId property.
     * 
     */
    public byte getTableId() {
        return tableId;
    }

    /**
     * Sets the value of the tableId property.
     * 
     */
    public void setTableId(byte value) {
        this.tableId = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public byte getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(byte value) {
        this.priority = value;
    }

    /**
     * Gets the value of the hardTimeout property.
     * 
     */
    public short getHardTimeout() {
        return hardTimeout;
    }

    /**
     * Sets the value of the hardTimeout property.
     * 
     */
    public void setHardTimeout(short value) {
        this.hardTimeout = value;
    }

    /**
     * Gets the value of the idleTimeout property.
     * 
     */
    public short getIdleTimeout() {
        return idleTimeout;
    }

    /**
     * Sets the value of the idleTimeout property.
     * 
     */
    public void setIdleTimeout(short value) {
        this.idleTimeout = value;
    }

    /**
     * Gets the value of the installHw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallHw() {
        return installHw;
    }

    /**
     * Sets the value of the installHw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallHw(String value) {
        this.installHw = value;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link Flow.Instructions }
     *     
     */
    public Flow.Instructions getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flow.Instructions }
     *     
     */
    public void setInstructions(Flow.Instructions value) {
        this.instructions = value;
    }

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link Flow.Match }
     *     
     */
    public Flow.Match getMatch() {
        return match;
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flow.Match }
     *     
     */
    public void setMatch(Flow.Match value) {
        this.match = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="instruction">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="apply-actions">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="action" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="output-action" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="output-node-connector" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                                 &lt;element name="max-length" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="set-queue-action" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                                 &lt;element name="queue-id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instruction"
    })
    public static class Instructions {

        @XmlElement(required = true)
        protected Flow.Instructions.Instruction instruction;

        /**
         * Gets the value of the instruction property.
         * 
         * @return
         *     possible object is
         *     {@link Flow.Instructions.Instruction }
         *     
         */
        public Flow.Instructions.Instruction getInstruction() {
            return instruction;
        }

        /**
         * Sets the value of the instruction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Flow.Instructions.Instruction }
         *     
         */
        public void setInstruction(Flow.Instructions.Instruction value) {
            this.instruction = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="apply-actions">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="action" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="output-action" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="output-node-connector" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                       &lt;element name="max-length" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="set-queue-action" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                       &lt;element name="queue-id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "order",
            "applyActions"
        })
        public static class Instruction {

            protected byte order;
            @XmlElement(name = "apply-actions", required = true)
            protected Flow.Instructions.Instruction.ApplyActions applyActions;

            /**
             * Gets the value of the order property.
             * 
             */
            public byte getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             */
            public void setOrder(byte value) {
                this.order = value;
            }

            /**
             * Gets the value of the applyActions property.
             * 
             * @return
             *     possible object is
             *     {@link Flow.Instructions.Instruction.ApplyActions }
             *     
             */
            public Flow.Instructions.Instruction.ApplyActions getApplyActions() {
                return applyActions;
            }

            /**
             * Sets the value of the applyActions property.
             * 
             * @param value
             *     allowed object is
             *     {@link Flow.Instructions.Instruction.ApplyActions }
             *     
             */
            public void setApplyActions(Flow.Instructions.Instruction.ApplyActions value) {
                this.applyActions = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="action" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="output-action" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="output-node-connector" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                             &lt;element name="max-length" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="set-queue-action" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                             &lt;element name="queue-id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "action"
            })
            public static class ApplyActions {

                protected List<Flow.Instructions.Instruction.ApplyActions.Action> action;

                /**
                 * Gets the value of the action property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the action property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAction().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Flow.Instructions.Instruction.ApplyActions.Action }
                 * 
                 * 
                 */
                public List<Flow.Instructions.Instruction.ApplyActions.Action> getAction() {
                    if (action == null) {
                        action = new ArrayList<Flow.Instructions.Instruction.ApplyActions.Action>();
                    }
                    return this.action;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="output-action" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="output-node-connector" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                   &lt;element name="max-length" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="set-queue-action" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                   &lt;element name="queue-id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "order",
                    "outputAction",
                    "setQueueAction"
                })
                public static class Action {

                    protected byte order;
                    @XmlElement(name = "output-action")
                    protected Flow.Instructions.Instruction.ApplyActions.Action.OutputAction outputAction;
                    @XmlElement(name = "set-queue-action")
                    protected Flow.Instructions.Instruction.ApplyActions.Action.SetQueueAction setQueueAction;

                    /**
                     * Gets the value of the order property.
                     * 
                     */
                    public byte getOrder() {
                        return order;
                    }

                    /**
                     * Sets the value of the order property.
                     * 
                     */
                    public void setOrder(byte value) {
                        this.order = value;
                    }

                    /**
                     * Gets the value of the outputAction property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Flow.Instructions.Instruction.ApplyActions.Action.OutputAction }
                     *     
                     */
                    public Flow.Instructions.Instruction.ApplyActions.Action.OutputAction getOutputAction() {
                        return outputAction;
                    }

                    /**
                     * Sets the value of the outputAction property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Flow.Instructions.Instruction.ApplyActions.Action.OutputAction }
                     *     
                     */
                    public void setOutputAction(Flow.Instructions.Instruction.ApplyActions.Action.OutputAction value) {
                        this.outputAction = value;
                    }

                    /**
                     * Gets the value of the setQueueAction property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Flow.Instructions.Instruction.ApplyActions.Action.SetQueueAction }
                     *     
                     */
                    public Flow.Instructions.Instruction.ApplyActions.Action.SetQueueAction getSetQueueAction() {
                        return setQueueAction;
                    }

                    /**
                     * Sets the value of the setQueueAction property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Flow.Instructions.Instruction.ApplyActions.Action.SetQueueAction }
                     *     
                     */
                    public void setSetQueueAction(Flow.Instructions.Instruction.ApplyActions.Action.SetQueueAction value) {
                        this.setQueueAction = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="output-node-connector" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *         &lt;element name="max-length" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "outputNodeConnector",
                        "maxLength"
                    })
                    public static class OutputAction {

                        @XmlElement(name = "output-node-connector")
                        protected byte outputNodeConnector;
                        @XmlElement(name = "max-length")
                        protected byte maxLength;

                        /**
                         * Gets the value of the outputNodeConnector property.
                         * 
                         */
                        public byte getOutputNodeConnector() {
                            return outputNodeConnector;
                        }

                        /**
                         * Sets the value of the outputNodeConnector property.
                         * 
                         */
                        public void setOutputNodeConnector(byte value) {
                            this.outputNodeConnector = value;
                        }

                        /**
                         * Gets the value of the maxLength property.
                         * 
                         */
                        public byte getMaxLength() {
                            return maxLength;
                        }

                        /**
                         * Sets the value of the maxLength property.
                         * 
                         */
                        public void setMaxLength(byte value) {
                            this.maxLength = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *         &lt;element name="queue-id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "queue",
                        "queueId"
                    })
                    public static class SetQueueAction {

                        protected byte queue;
                        @XmlElement(name = "queue-id")
                        protected byte queueId;

                        /**
                         * Gets the value of the queue property.
                         * 
                         */
                        public byte getQueue() {
                            return queue;
                        }

                        /**
                         * Sets the value of the queue property.
                         * 
                         */
                        public void setQueue(byte value) {
                            this.queue = value;
                        }

                        /**
                         * Gets the value of the queueId property.
                         * 
                         */
                        public byte getQueueId() {
                            return queueId;
                        }

                        /**
                         * Sets the value of the queueId property.
                         * 
                         */
                        public void setQueueId(byte value) {
                            this.queueId = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ethernet-match">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ethernet-type">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ethernet-destination">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ethernetMatch"
    })
    public static class Match {

        @XmlElement(name = "ethernet-match", required = true)
        protected Flow.Match.EthernetMatch ethernetMatch;

        /**
         * Gets the value of the ethernetMatch property.
         * 
         * @return
         *     possible object is
         *     {@link Flow.Match.EthernetMatch }
         *     
         */
        public Flow.Match.EthernetMatch getEthernetMatch() {
            return ethernetMatch;
        }

        /**
         * Sets the value of the ethernetMatch property.
         * 
         * @param value
         *     allowed object is
         *     {@link Flow.Match.EthernetMatch }
         *     
         */
        public void setEthernetMatch(Flow.Match.EthernetMatch value) {
            this.ethernetMatch = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ethernet-type">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ethernet-destination">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ethernetType",
            "ethernetDestination"
        })
        public static class EthernetMatch {

            @XmlElement(name = "ethernet-type", required = true)
            protected Flow.Match.EthernetMatch.EthernetType ethernetType;
            @XmlElement(name = "ethernet-destination", required = true)
            protected Flow.Match.EthernetMatch.EthernetDestination ethernetDestination;

            /**
             * Gets the value of the ethernetType property.
             * 
             * @return
             *     possible object is
             *     {@link Flow.Match.EthernetMatch.EthernetType }
             *     
             */
            public Flow.Match.EthernetMatch.EthernetType getEthernetType() {
                return ethernetType;
            }

            /**
             * Sets the value of the ethernetType property.
             * 
             * @param value
             *     allowed object is
             *     {@link Flow.Match.EthernetMatch.EthernetType }
             *     
             */
            public void setEthernetType(Flow.Match.EthernetMatch.EthernetType value) {
                this.ethernetType = value;
            }

            /**
             * Gets the value of the ethernetDestination property.
             * 
             * @return
             *     possible object is
             *     {@link Flow.Match.EthernetMatch.EthernetDestination }
             *     
             */
            public Flow.Match.EthernetMatch.EthernetDestination getEthernetDestination() {
                return ethernetDestination;
            }

            /**
             * Sets the value of the ethernetDestination property.
             * 
             * @param value
             *     allowed object is
             *     {@link Flow.Match.EthernetMatch.EthernetDestination }
             *     
             */
            public void setEthernetDestination(Flow.Match.EthernetMatch.EthernetDestination value) {
                this.ethernetDestination = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "address"
            })
            public static class EthernetDestination {

                @XmlElement(required = true)
                protected String address;

                /**
                 * Gets the value of the address property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddress() {
                    return address;
                }

                /**
                 * Sets the value of the address property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddress(String value) {
                    this.address = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "type"
            })
            public static class EthernetType {

                protected short type;

                /**
                 * Gets the value of the type property.
                 * 
                 */
                public short getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 */
                public void setType(short value) {
                    this.type = value;
                }

            }

        }

    }

}
