//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 12:18:32 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:opendaylight:flow:inventory", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sdn.app;
