# Generated by Django 2.2.1 on 2019-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iperf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('start', models.CharField(max_length=200)),
                ('stop', models.CharField(max_length=200)),
                ('threads', models.IntegerField()),
                ('interval', models.CharField(max_length=200)),
                ('transfer', models.CharField(max_length=100)),
                ('bandwidth', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
