# Generated by Django 2.2.1 on 2019-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_iperf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iperf',
            name='data',
            field=models.CharField(max_length=1000),
        ),
    ]
