# Generated by Django 2.2.1 on 2019-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190520_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=200)),
                ('stop', models.CharField(max_length=200)),
                ('old', models.CharField(max_length=200)),
                ('new', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
    ]
