# Generated by Django 2.2.1 on 2019-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_packets_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iperf',
            name='data',
            field=models.CharField(max_length=10000),
        ),
    ]
